### ISSUE TITLE
Failed initializing MeCab 

### ISSUE THREAD

**Issue by Mukei** [YutaroOgawa/BERT_Japanese_Google_Colaboratory#1]
記事とコードを共有していただき、ありがとうございます！
大変参考になります。

あいにく、Colabで *[1_Japanese_BERT_on_Google_Colaboratory.ipynb](https://github.com/YutaroOgawa/BERT_Japanese_Google_Colaboratory/blob/master/1_Japanese_BERT_on_Google_Colaboratory.ipynb)* 実行をしようとしたら、複数エラーが出てしまったので、再現できませんでした。

以下は１個目のエラーです。

```
m=MeCab.Tagger("-Ochasen")
```
や

```
m=MeCab.Tagger("-Oyomi")
```

で以下のエラーがあります。

```

----------------------------------------------------------

Failed initializing MeCab. Please see the README for possible solutions:

    https://github.com/SamuraiT/mecab-python3#common-issues

If you are still having trouble, please file an issue here, and include the
ERROR DETAILS below:

    https://github.com/SamuraiT/mecab-python3/issues

issueを英語で書く必要はありません。

------------------- ERROR DETAILS ------------------------
arguments: -Ochasen
error message: [ifs] no such file or directory: /usr/local/etc/mecabrc
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-a0984118ca4f> in <module>()
      1 import MeCab
      2 
----> 3 m=MeCab.Tagger("-Ochasen")

/usr/local/lib/python3.6/dist-packages/MeCab/__init__.py in __init__(self, rawargs)
    122 
    123         try:
--> 124             super(Tagger, self).__init__(args)
    125         except RuntimeError:
    126             error_info(rawargs)

RuntimeError: 

```

NEologdの辞書を使うと問題ないです。

**Comment by Mukei** [comment]
MeCabのバージョンを`0.996.6rc2`にすると解決できました。
バージョン1.0以降でbreaking changeがあったようです。

```!pip install mecab-python3==0.996.6rc2```

**Comment by YutaroOgawa** [comment]
@Mukei さま

大変貴重な情報をありがとうございます。
とても参考になります。

ありがとうございました。

**Comment by Mukei** [comment]
@YutaroOgawa 
いいえ、こちらこそ、ありがとうございます！

この[スレード](https://github.com/huggingface/transformers/pull/5375)でMeCab 1.0のBreaking changesなどの話されています。
huggingfaceのほうでも、簡単にMeCab >= 1.0に行かなそうですね…

**Comment by YutaroOgawa** [comment]
@Mukei　さま

誠にありがとうございます。
とても助かります。

本家Huggingfaceさん側でも大変ですね
（彼からしたら、日本語の形態素解析の1パッケージの話まで、大変だ・・・）

本内容とても重要なものでした。
誠にありがとうございます。

プルリクエストもいただき、ありがとうございました。
Mergeいたしました。
